#!/bin/bash

queueName=$1
if $queueName = 'ALL_QUEUES';then
   $queueName = '*'
fi


sudo -u www-data -E QUEUE=$queueName VERBOSE=1 nohup rake environment resque:work& > log/resque_worker_$1_$2.log &

echo $(($! - 1)) > tmp/pids/resque_$1_$2.pid


