source 'https://rubygems.org'

gem 'rails', '3.2.7'
gem 'pg'


group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer', platforms: :ruby
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'standup', path: '../../'
end

gem 'jquery-rails'
